version: "3"

services:
  app:
    build: .
    volumes:
      - ./app:/home/app
    ports:
      - "8080:8080"
    working_dir: /home/app
    command: npm run serve --dev
    depends_on:
      - api

  api:
    build: api
    volumes:
      - ./api:/home/api
    ports:
      - "5000:5000"
    command: python /home/api/api.py